name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  changes:
    name: Detect Changed Files
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changed-files.outputs.files }}
    steps:
      - uses: actions/checkout@v6
      - id: changed-files
        uses: dorny/paths-filter@v4
        with:
          filters: |
            files:
              - '.github/workflows/nix.yaml'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'crates/**'
              - 'ncro/**'
              - 'nix/package.nix'
              - 'nix/module.nix'
              - 'nix/shell.nix'
              - 'flake.nix'
              - 'flake.lock'

  build:
    name: Build
    needs: changes
    if: ${{ needs.changes.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Build ncro package
        run: nix build .# -L --no-link
