name: Nix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  changes:
    name: Detect Changed Files
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changed-files.outputs.files }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - id: changed-files
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4
        with:
          filters: |
            files:
              - '.github/workflows/nix.yaml'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'crates/**'
              - 'ncro/**'
              - 'nix/package.nix'
              - 'nix/module.nix'
              - 'nix/shell.nix'
              - 'flake.nix'
              - 'flake.lock'

  build:
    name: Build
    needs: changes
    if: ${{ needs.changes.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - name: Build ncro package
        run: nix build .# -L --no-link
