name: Publish Built Binaries

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          prerelease: false
          generate_release_notes: true

  build-release:
    needs: create-release
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            name: ncro-linux-amd64
          - os: ubuntu-24.04-arm
            name: ncro-linux-arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31

      - name: Build binary
        run: nix build .#ncro -L

      - name: Prepare binary (Unix)
        run: |
          cp result/bin/ncro ${{ matrix.name }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ matrix.name }}

  generate-checksums:
    needs: [create-release, build-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Download Assets
        uses: robinraju/release-downloader@v1
        with:
          tag: ${{ github.ref_name }}
          fileName: "ncro-*"
          out-file-path: "."

      - name: Generate checksums
        run: |
          sha256sum ncro-* > SHA256SUMS

      - name: Upload Checksums
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: SHA256SUMS
